name = "KenwardRoger"
uuid = "fb531da0-582c-4a62-80cc-836e12ba9c31"
authors = ["Arno Strouwen", "José Núñez Ares"]
version = "0.0.1-DEV"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MixedModels = "ff71e718-51f3-5ec2-a782-8ffcbfa3c316"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Aqua = "0.8"
CSV = "0.10.15"
DataFrames = "1.7.0"
Distributions = "0.25.113"
ForwardDiff = "0.10.38"
JET = "0.9"
JSON3 = "1.14.1"
LinearAlgebra = "1.10.0"
MixedModels = "4.27.0"
StaticArrays = "1.9.8"
Test = "1.10"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "JET", "Test"]
