name = "MixedModelsSmallSample"
uuid = "fb531da0-582c-4a62-80cc-836e12ba9c31"
version = "0.0.3"
authors = ["Arno Strouwen", "José Núñez Ares"]

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
MixedModels = "ff71e718-51f3-5ec2-a782-8ffcbfa3c316"
StatsAPI = "82ae8749-77ed-4fe6-ae5f-f523153014b0"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
Distributions = "0.25.49"
LinearAlgebra = "1.10"
Markdown = "1.10.0"
MixedModels = "4.22, 5"
StatsAPI = "1.5"
StatsBase = "0.33.15, 0.44, 0.34"
julia = "1.10"
