[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
MixedModels = "ff71e718-51f3-5ec2-a782-8ffcbfa3c316"
MixedModelsSmallSample = "fb531da0-582c-4a62-80cc-836e12ba9c31"

[sources.MixedModelsSmallSample]
path = ".."

[compat]
CSV = "0.10"
DataFrames = "1"
Documenter = "1"
MixedModels = "5"
MixedModelsSmallSample = "0.0.5"
julia = "1.12"
